version: 1.0.{build}
build:
  project: .\Sitecore.React.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
test: off
before_build:
  - nuget restore Sitecore.React.sln
image: Visual Studio 2017
nuget:
  project_feed: true
deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/sitecore-react-vgd5n8xvyw00/api/v2/package
    api_key:
      secure: 7gjxcs5gkjkq1ltqycvdmipt
    artifact: /.*\.nupkg/