version: 1.0.{build}
build:
  verbosity: minimal
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
test: off
before_build:
  - nuget restore Sitecore.React.sln
after_build:
  - ps: .\build\pack.ps1